CREATE TABLE IF NOT EXISTS Colour (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Car (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    plate_number VARCHAR(255),
    brand VARCHAR(255),
    colour_id BIGINT,
    model VARCHAR(255),
    car_type ENUM('XL', 'SEDAN', 'HATCHBACK', 'COMPACT_SUV', 'SUV'),
    driver_id BIGINT UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE Car
    ADD CONSTRAINT fk_car_colour FOREIGN KEY (colour_id) REFERENCES Colour(id) ON DELETE SET NULL;

ALTER TABLE Car
    ADD CONSTRAINT fk_car_driver FOREIGN KEY (driver_id) REFERENCES Driver(id) ON DELETE SET NULL;